Update program algorithm
rafixxx4k/impreza-na-polanie pull request #2
Opened 2024-04-17 16:38 UTC by StaGlo

Major algorithm changes.
Improved events handling and performance.
Reduce communication complexity.
Introduce necessary variables.

2024-04-17 16:42 UTC, StaGlo commented
@TypicalAM, we'd appreciate your thoughts on the proposed changes. 

Your feedback will be thoroughly considered.

2024-04-18 13:37 UTC, TypicalAM requested changes
LGTM for the most part!

2024-04-18 13:37 UTC, TypicalAM commented on README.md
> +Z rozszerzonej zasady szufladkowej Dirichleta, pewne jest, że jakaś impreza dojdzie do skutku, wtedy i tylk wtedy, gdy liczba zajączków jest większa od iloczynu liczby polan i pojemności polan pomnie
Should be "i tylko wtedy"

2024-04-18 14:42 UTC, rafixxx4k requested changes

2024-04-18 14:42 UTC, rafixxx4k commented on README.md
> +- Gdy wykryje że lista zwierząt biorących udział w imprezie jest pełna wysyła do wszystkich uczestników wiadomość `ALCO`, zerują licznik `alco_count` i przechodzi do stanu **MOREALCO**
Since alco_count is a variable should be in *italics*

2024-04-18 14:42 UTC, rafixxx4k commented on README.md
> +    - `ENTER`: zwiększenie licznika `enter_count`
Same as above

2024-04-18 18:11 UTC, StaGlo commented
I have fixed all the issues mentioned above.
Please, review the code and approve if you thinks it's fine.

2024-04-18 18:38 UTC, rafixxx4k approved these changes

2024-04-18 18:38 UTC, merged